#! /bin/bash


# Binarize all the ROI_masks
mskPthIn="/media/h/P04/Data/S04/Ses01/03_GLM/SriPlay/ROI_masks/func_space/masks/"

strPathOrig=$PWD

cd ${mskPthIn}
Files=( $(ls | grep .nii.gz) )
numFiles=${#Files[@]}
numFiles=$(($numFiles - 1))
cd ${strPathOrig}

for i in $(seq 0 $numFiles); do

  mri_binarize \
  --i ${mskPthIn}${Files[${i}]} \
  --o ${mskPthIn}${Files[${i}]} \
  --min 0.5

done


# # Binarize all the ROI_masks
# mskPthIn="/media/h/P04/Data/S04/Ses01/03_GLM/SriPlay/ROI_masks/func_space/"
#
# strPathOrig=$PWD
#
# cd ${mskPthIn}
# Files=( $(ls | grep .nii.gz) )
# numFiles=${#Files[@]}
# numFiles=$(($numFiles - 1))
# cd ${strPathOrig}
#
# for i in $(seq 0 $numFiles); do
#
#   mri_binarize \
#   --i ${mskPthIn}${Files[${i}]} \
#   --o ${mskPthIn}${Files[${i}]} \
#   --min 0.5
#
# done
